/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const ElNotificatio: typeof import('element-plus/es')['ElNotificatio']
  const ElNotification: typeof import('element-plus/es')['ElNotification']
}
